student_name = input("Enter student name: ")
student_id = input("Enter student ID: ")
department = input("Enter department: ")
year = int(input("Enter year: "))
university = input("Enter university: ")
phone = input("Enter phone number: ")

print()
print("+--------------------------------+")
print("|       AKIBA STUDENT CARD       |")
print("+--------------------------------+")
print(f"| Name:       {student_name:<18}|")
print(f"| ID:         {student_id:<18}|")
print(f"| Department:  {department:<17}|")
print(f"| Year:       {year:<18}|")
print(f"| University:  {university:<17}|")
print(f"| Phone:      {phone:<18}|")
print("+--------------------------------+")