full_name = input("Enter your full name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite_language = input("Enter your favorite programming language: ")
programming_goal = input("Enter your programming goal: ")

print()
print("========================================")
print("        STUDENT INTRODUCTION")
print("========================================")

print(f"My name is {full_name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite_language}.")

print()
print("My programming goal:")
print(programming_goal)

print()
print("========================================")